---
title: Hello Geogebra!
description: An example of grading Geogebra code with Node.js
instructions: |
  <p>Alla on kuva kolmion muotoisesta pöydästä. Pöytä halutaan seisomaan vain yhden jalan varassa, 
  jolloin jalka pitäisi sijoittaa pöytälevyn painopisteeseen. Määritä pöytälevyn painopiste alla olevalla GeoGebra-appletilla. 
  Varmista, että nimeät painopisteen kirjaimella D.

    <iframe id="ggbFrame_v2" src="/static/default/_static/child.html" onload="postMsg();" width="1000" height="600" frameborder="0"></iframe>

    <script type="text/javascript">
      function postMsg() {
        var ggbFrame = document.getElementById("ggbFrame_v2");
        // TODO: Hello Teacher, edit cmd! 
        // TODO: The very same cmds that you inserted in the GeoGebra web UI apply.
        // TODO: semi-colon(;) separates the commands.
        var cmd="A = (-4, -2);B: (1, 3);C: (3, 0);SetFixed(A,true);SetFixed(B,true);SetFixed(C,true);k1: Polygon[A, B, C];c: Segment[A, B, k1];a: Segment[B, C, k1];b: Segment[C, A, k1];ShowLabel(A,false);ShowLabel(B,false);ShowLabel(C,false)";
        var par = '{"appName": "graphing", "allowStyleBar": false, "showToolBar": true, "showAlgebraInput": true, "showMenuBar": true}';
        // TODO: do not remove \n - it is needed to separate the fields
        ggbFrame.contentWindow.postMessage(cmd+"\n"+par, '*');
      };
      var eventMethod = window.addEventListener ? "addEventListener" : "attachEvent";
      var eventer = window[eventMethod];
      var messageEvent = eventMethod === "attachEvent" ? "onmessage" : "message";
      eventer(messageEvent, function (e) {
        var data = (typeof e.data) === "string" ? e.data : "";
        document.getElementById("v2_id").style.display = "none";
        document.getElementById("v2_id").value = data;
      });
    </script>
  </p>
# acceptPost tuottaa tekstikentän sivulle
# tiedoston palautuslomakkeen sijaan
view_type: access.types.stdasync.acceptPost 
fields: # näiden täytyy olla valideja HTML-formien attribuutteja
  - name: v2 # Lomakkeen nimi verkkosivulla, täytyy olla yksikäsitteinen ja sopia yhteen v_id:n kanssa (ks.yllä, kahdessa kohtaa ja alla run.sh:n jälkeen)
    required: True

container:
  image: apluslms/grade-nodejs:11-2.7
  mount: exercises/geogebra-example
  cmd: /exercise/run.sh v2 '{"D":"(-0.7,-0.3)"}'
