title: Hello Abitti!
description: An example of grading Abitti code with Node.js
instructions: |
  <p>This page shows how to register JavaScript functions as
    listeners to changes in a Abitti
    editor.
    <iframe id="abittiFrame" src="https://tie-lukioplus.rd.tuni.fi/abitti/" width="1000" height="600" frameborder="0"></iframe>

    <script type="text/javascript">
      var eventMethod = window.addEventListener ? "addEventListener" : "attachEvent";
      var eventer = window[eventMethod];
      var messageEvent = eventMethod === "attachEvent" ? "onmessage" : "message";
      eventer(messageEvent, function (e) {
        console.log(e.data);
        var data = (typeof e.data) === "string" ? e.data : "";
        # document.getElementById("abitti_v_id").style.display = "none";
        document.getElementById("abitti_v_id").value = data;
      });
    </script>
  </p>
# acceptPost tuottaa tekstikentän sivulle
# tiedoston palautuslomakkeen sijaan
view_type: access.types.stdasync.acceptPost 
fields: # näiden täytyy olla valideja HTML-formien attribuutteja
  - name: abitti_v # Lomakkeen nimi verkkosivulla, täytyy olla yksikäsitteinen ja sopia yhteen v_id:n kanssa (ks.yllä) ja run.sh:n kanssa (ks.alla)
    required: True

container:
  image: apluslms/grade-nodejs:11-2.7
  mount: exercises/abitti-example
  cmd: /exercise/run.sh abitti_v '{"A":1,"B":2}'
